## DATBASE ##
DATABASE_IP = " servinfo-mariadb "
DATABASE_USER = "aazzouz"
DATABASE_PASSWORD = "aazzouz"
DATBASE_NAME = "DBaazzouz"

## OTHERS ##
STRING_MAX_SIZE = 255
STRING_MIDLE_SIZE = 200
STRING_LITTLE_SIZE = 50
STRING_TEL_SIZE = 13